### ISSUE TITLE
Option to disable elapsed time output?

### ISSUE THREAD

**Issue by sharkdp** [oovm/jupyter-protocol#2]
Thank you very much for publishing this crate! I am building a jupyter kernel for a language of mine and it has served me great so far.

The kernel always sends a "Elapsed time" message:

https://github.com/oovm/jupyter-protocol/blob/baffcc51d9bc21c2a5fb2e8e0bda099ab2ba40f8/projects/jupyter/src/client/mod.rs#L207-L221

I personally find it a bit annoying in the output, as it's not really relevant for my kernel (which typically responds extremely fast). Would it be possible to make this configurable?

**Comment by oovm** [comment]
just send empty running time, this does not cause a heap allocation.

```rust
    fn running_time(&self, _: f64) -> String {
        String::new()
    }
```

**Comment by oovm** [comment]
Or do you want to use env variables to control?

**Comment by sharkdp** [comment]
Ah, no. I didn't realize I could just customize `running_time` in my trait implementation and return an empty string. This solution is fine for me. Thank you!
