### ISSUE TITLE
Sending images does not work

### ISSUE THREAD

**Issue by sharkdp** [oovm/jupyter-protocol#3]
When trying to send `RgbaImage`s from the kernel, the images are not displayed correctly in the frontend.

I believe the reason is the following: Sending PNG images is currently implemented by encoding them in a base64 data url:

https://github.com/oovm/jupyter-protocol/blob/baffcc51d9bc21c2a5fb2e8e0bda099ab2ba40f8/projects/jupyter/src/value_type/for_image.rs#L16-L17

but then later the message is sent with the `image/png` mime type here, which (presumably) messes things up because Jupyter interprets the HTML code as PNG content:

https://github.com/oovm/jupyter-protocol/blob/baffcc51d9bc21c2a5fb2e8e0bda099ab2ba40f8/projects/jupyter/src/value_type/for_image.rs#L23

Everything works fine for me, if I change that mime type to `text/html`. I'm not sure if there is another (better) fix where `image/png` is used but the content is changed to only being the PNG content.

**Comment by oovm** [comment]
`image/png` is a standard-compliant implementation, but it seems that vscode is not intended to support it.

https://github.com/microsoft/vscode-jupyter/issues/11532

For compatibility, I will change to `text/html`

**Comment by oovm** [comment]
@sharkdp  Can you help me test whether the images of `0.1.10` can be displayed normally?

**Comment by sharkdp** [comment]
The fix looks good, but somehow I now get
```
   Compiling jupyter v0.1.12
error[E0446]: crate-private type `Connection<S>` in public interface
   --> /home/shark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jupyter-0.1.12/src/jupyter_message/mod.rs:211:5
    |
211 |     pub async fn send_state<S: SocketSend>(&self, connection: Arc<Mutex<Connection<S>>>, busy: bool) -> JupyterResult<()> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
    |
   ::: /home/shark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jupyter-0.1.12/src/connection.rs:19:1
    |
19  | pub(crate) struct Connection<S> {
    | ------------------------------- `Connection<S>` declared as crate-private
```

**Comment by oovm** [comment]
This is very strange, if there is a problem with compilation, how can it be successfully released?

I made some breaking updates, the version number came to 0.2.0, now each message must be accompanied by a parent message, and allows the use of `send_stream` to send stdio events.

https://github.com/oovm/jupyter-protocol/blob/a7a78fd133b73b951a2c79fced53228bb102a7a4/projects/jupyter-calculator/src/lib.rs#L36-L49

**Comment by oovm** [comment]
This interface should be exposed in the new version

https://github.com/oovm/jupyter-protocol/blob/a7a78fd133b73b951a2c79fced53228bb102a7a4/projects/jupyter/src/connection.rs#L20-L24

**Comment by sharkdp** [comment]
It works great now, thank you very much!
